-- ============================================
-- Cloud Kitchen & Food Delivery Management System
-- Sample SQL Queries
-- ============================================

-- 1. View all restaurants
SELECT * FROM Restaurants;

-- 2. View all customers
SELECT * FROM Customers;

-- 3. View all menu items
SELECT * FROM Menus;

-- 4. View all orders
SELECT * FROM Orders;

-- 5. Find pending orders
SELECT *
FROM Orders
WHERE status = 'Pending';

-- 6. Top rated restaurants
SELECT restaurant_name, rating
FROM Restaurants
ORDER BY rating DESC;

-- 7. Customer Order Details
SELECT
    c.name AS Customer,
    r.restaurant_name AS Restaurant,
    o.total_amount,
    o.status
FROM Orders o
JOIN Customers c
ON o.customer_id = c.customer_id
JOIN Restaurants r
ON o.restaurant_id = r.restaurant_id;

-- 8. Revenue Generated by Each Restaurant
SELECT
    r.restaurant_name,
    SUM(o.total_amount) AS Total_Revenue
FROM Orders o
JOIN Restaurants r
ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_name
ORDER BY Total_Revenue DESC;

-- 9. Total Orders by Restaurant
SELECT
    r.restaurant_name,
    COUNT(o.order_id) AS Total_Orders
FROM Orders o
JOIN Restaurants r
ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_name;

-- 10. Average Restaurant Rating
SELECT AVG(rating) AS Average_Rating
FROM Restaurants;

-- 11. Today's Orders
SELECT * FROM vw_todays_orders;

-- 12. Top Restaurants
SELECT * FROM vw_top_restaurants;

-- 13. Pending Deliveries
SELECT * FROM vw_pending_deliveries;

-- 14. Total Customers
SELECT COUNT(*) AS Total_Customers
FROM Customers;

-- 15. Payment Method Analysis
SELECT
    payment_method,
    COUNT(*) AS Total_Transactions
FROM Payments
GROUP BY payment_method;

-- 16. Driver Performance
SELECT
    d.driver_name,
    COUNT(de.delivery_id) AS Deliveries_Completed
FROM Drivers d
JOIN Deliveries de
ON d.driver_id = de.driver_id
GROUP BY d.driver_name
ORDER BY Deliveries_Completed DESC;

-- 17. Restaurant Rating Analysis
SELECT
    restaurant_name,
    rating
FROM Restaurants
WHERE rating >= 4.5
ORDER BY rating DESC;

-- 18. Coupon Details
SELECT * FROM Coupons;

-- 19. Orders with Payments
SELECT
    o.order_id,
    c.name,
    p.payment_method,
    p.payment_status
FROM Orders o
JOIN Customers c
ON o.customer_id = c.customer_id
JOIN Payments p
ON o.order_id = p.order_id;

-- 20. Orders with Deliveries
SELECT
    o.order_id,
    d.driver_name,
    de.delivery_status
FROM Orders o
JOIN Deliveries de
ON o.order_id = de.order_id
JOIN Drivers d
ON de.driver_id = d.driver_id;
